apiVersion: v1
kind: PersistentVolume
metadata:
  name: static-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  csi:
    driver: ebs.csi.aws.com
    fsType: ext4
    volumeHandle: vol-0209efe46020043c2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: static-pv
spec:
  storageClassName: "" # Empty string must be explicitly set otherwise default StorageClass will be set
  volumeName: static-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    purpose: ebs-service
spec:
  nodeSelector:
    topology.kubernetes.io/zone: us-east-1b
  containers:
    - name: nginx
      image: nginx

      volumeMounts:
        - name: nginx-html
          mountPath: /usr/share/nginx/html
  volumes:
    - name: nginx-html
      persistentVolumeClaim:
        claimName: static-pv
---
apiVersion: v1
kind: Service
metadata:
  name: ebs-service
spec:
  type: LoadBalancer
  selector:
    purpose: ebs-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80 #container port
      nodePort: 30007
