apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: roboshop-ebs
reclaimPolicy: Retain # default value is Delete
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: roboshop-ebs
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: roboshop-ebs
  resources:
    requests:
      storage: 4Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    purpose: ebs-dynamic
spec:
  containers:
    - name: nginx
      image: nginx

      volumeMounts:
        - name: nginx-html
          mountPath: /usr/share/nginx/html
  volumes:
    - name: nginx-html
      persistentVolumeClaim:
        claimName: roboshop-ebs
---

---
apiVersion: v1
kind: Service
metadata:
  name: ebs-dynamic
spec:
  type: LoadBalancer
  selector:
    purpose: ebs-dynamic
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80 #container port
      nodePort: 30008
