apiVersion: v1
kind: Pod
metadata: 
  name: multi-container
  labels:
    kind: multi-container
    project: roboshop
spec:
  containers:
    - name: nginx
      image: nging
    - name: alpine
      image: alpine:9
      command: ["sleep","100"]
