apiVersion: v1
kind: Pod
metadata:
  name: env
  labels:
    purpose: env creation
spec: 
  containers:
    - name: nginx
      image: nginx
env:
 - name: course
   value: devop
 - name: trainer
   value: siva
    
    