apiVersion: v1
kind: Service
metadata:
  name: service-pod  
spec:
   selector:
     project: roboshop
     component: frontend
     env: dev
   ports:
    - protocol: TCP
      port: 80
      targetPort: 80 #container port 
