apiVersion: v1
kind: Service
metadata:
  name: np-service-demo
spec:
  type: NodePort
  selector:
    name: nodeportdemo
    componentname: frontend
    environment: dev
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
