apiVersion: v1
kind: Service
metadata:
  name: np-service-demo
spec:
  type: LoadBalancer
  selector:
    name: lbdemo
    componentname: frontend
    environment: dev
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      NodePort: 30007
