
# Service for Headless service
apiVersion: v1
kind: Service
metadata: 
  name: nginx-headless
  labels:
    app: nginx
    purpose: statefull
spec: 
  selector:
      app: nginx
      purpose: statefull
  clusterIP: None 
  ports:
    - port: 80
      name: web
# Service for clusterip
---
apiVersion: v1
kind: Service
metadata:
  name: statefull-demo
  labels:
    app: nginx
    purpose: statefull
spec:
  selector:
    app: nginx
    purpose: statefull
  ports:
    - port: 80
      name: web
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx # has to match .spec.template.metadata.labels
      purpose: statefull
  serviceName: "nginx-headless"
  replicas: 3 # by default is 1
  template:
    metadata:
      labels:
        app: nginx # has to match .spec.selector.matchLabels
        purpose: statefull
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
          
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "roboshop-ebs"
      resources:
        requests:
          storage: 1Gi