apiVersion: v1
kind: pod
metadata: 
  name: annotations
  namespace: roboshop-dev
  annotations:
     jenkins.url: "http://jenkins.joindevops.com/build/job/5"
     imageregistry: "https://hub.docker.com/"
spec:
  containers:
    - name: nginx
      image: nginx